### ISSUE TITLE
win10 英文系统显示乱码

### ISSUE THREAD

**Issue by Cairl** [yijianguanzhu/douyu-hongbao#7]
![image](https://user-images.githubusercontent.com/20336299/156403936-b25b3613-2be4-4b81-a540-548134ca8884.png)

除了要反馈一下这个以外，还希望能增加个后台功能

**Comment by yijianguanzhu** [comment]
@Cairl 程序控制台输出的编码格式是GBK的，你改一下系统控制台的编码格式就行。

![微信截图_20220304091326](https://user-images.githubusercontent.com/68835311/156680579-23871464-4afa-41d5-afb5-71baeac483c4.png)
