### ISSUE TITLE
希望能变更送礼时间

### ISSUE THREAD

**Issue by Cairl** [yijianguanzhu/douyu-hongbao#9]
希望下个版本能将送礼时刻改成周六周日全天赠送，检测到周末就可以送，不然定时几点钟容易错过

**Comment by yijianguanzhu** [comment]
@Cairl 这款工具本意是需要一直运行的，这样才会发挥最大价值；另外赠送荧光棒功能，在周日错过20点之后，会在21点送出，仍然错过则小时数会依次递增，直到23点后，会马上送出。理论上一直运行的工具是不会错过送荧光棒时机的。
